"""empty message

Revision ID: 200e5c3ca500
Revises: 3176fce5c48d
Create Date: 2020-04-26 12:08:49.883386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '200e5c3ca500'
down_revision = '3176fce5c48d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'active')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
