"""empty message

Revision ID: 2033eddb5a46
Revises: 650a32600b4c
Create Date: 2020-03-07 16:43:32.478117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2033eddb5a46'
down_revision = '650a32600b4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('test', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cards', 'test')
    # ### end Alembic commands ###
