"""empty message

Revision ID: 22a4a22e10f9
Revises: 7b8865ca0e6e
Create Date: 2020-01-06 19:58:48.169649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22a4a22e10f9'
down_revision = '7b8865ca0e6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('value', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('card_usage')
    op.add_column('cards', sa.Column('collection_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'cards', 'collections', ['collection_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cards', type_='foreignkey')
    op.drop_column('cards', 'collection_id')
    op.create_table('card_usage',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('card_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('room_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], name='card_usage_card_id_fkey'),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], name='card_usage_room_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='card_usage_pkey')
    )
    op.drop_table('collections')
    # ### end Alembic commands ###
