"""empty message

Revision ID: 3f55b3f86f9c
Revises: 8e05634edf07
Create Date: 2020-06-08 22:23:27.273374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f55b3f86f9c'
down_revision = '8e05634edf07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('round_count', sa.Integer(), nullable=True))
    op.drop_column('games', 'round_number')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('round_number', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('games', 'round_count')
    # ### end Alembic commands ###
