"""empty message

Revision ID: 55063cfaebce
Revises: 6c4481e08cb1
Create Date: 2019-12-20 13:42:56.922035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55063cfaebce'
down_revision = '6c4481e08cb1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('scores', sa.String(length=65536), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rooms', 'scores')
    # ### end Alembic commands ###
