"""empty message

Revision ID: 650a32600b4c
Revises: 95433d32beee
Create Date: 2020-03-07 16:39:19.548694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '650a32600b4c'
down_revision = '95433d32beee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('game_data', sa.String(length=1024), nullable=True))
    op.drop_column('rooms', 'data')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('data', sa.VARCHAR(length=1024), autoincrement=False, nullable=True))
    op.drop_column('rooms', 'game_data')
    # ### end Alembic commands ###
