"""empty message

Revision ID: 6688f98a5ab1
Revises: a076cc3b94b5
Create Date: 2020-04-26 11:48:44.925715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6688f98a5ab1'
down_revision = 'a076cc3b94b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('discarded_at', sa.DateTime(), nullable=True))
    op.drop_column('rooms', 'game_data')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('game_data', sa.VARCHAR(length=500000), autoincrement=False, nullable=True))
    op.drop_column('rooms', 'discarded_at')
    # ### end Alembic commands ###
