"""empty message

Revision ID: 69326a74ab0e
Revises: 71d6a3da5f2b
Create Date: 2019-12-15 18:56:13.628679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69326a74ab0e'
down_revision = '71d6a3da5f2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('association', sa.Column('date_joined', sa.DateTime(), nullable=True))
    op.drop_column('association', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('association', sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('association', 'date_joined')
    # ### end Alembic commands ###
