"""empty message

Revision ID: 6c4481e08cb1
Revises: 80cc6175a0ab
Create Date: 2019-12-19 00:13:38.904929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c4481e08cb1'
down_revision = '80cc6175a0ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('card_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('card_id', sa.Integer(), nullable=True),
    sa.Column('room_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('black_game_cards')
    op.drop_table('white_game_cards')
    op.add_column('rooms', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rooms', 'created_at')
    op.create_table('white_game_cards',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('card_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('room_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], name='white_game_cards_card_id_fkey'),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], name='white_game_cards_room_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='white_game_cards_pkey')
    )
    op.create_table('black_game_cards',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('card_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('room_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], name='black_game_cards_card_id_fkey'),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], name='black_game_cards_room_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='black_game_cards_pkey')
    )
    op.drop_table('card_usage')
    # ### end Alembic commands ###
