"""empty message

Revision ID: 6dce884bb111
Revises: 69326a74ab0e
Create Date: 2019-12-16 00:57:31.166572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6dce884bb111'
down_revision = '69326a74ab0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('association', sa.Column('id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('association', 'id')
    # ### end Alembic commands ###
