"""empty message

Revision ID: 71d6a3da5f2b
Revises: 3ca79a75fb14
Create Date: 2019-12-15 18:47:50.015930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71d6a3da5f2b'
down_revision = '3ca79a75fb14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('association', sa.Column('id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('association', 'id')
    # ### end Alembic commands ###
