"""empty message

Revision ID: 766d485f36a0
Revises: 39e8616df4e3
Create Date: 2020-01-18 18:36:31.532175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '766d485f36a0'
down_revision = '39e8616df4e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collections', sa.Column('is_deletable', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('collections', 'is_deletable')
    # ### end Alembic commands ###
