"""empty message

Revision ID: 786586988b1a
Revises: 06760685d24b
Create Date: 2020-03-07 16:54:16.751008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '786586988b1a'
down_revision = '06760685d24b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cards', 'name',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=128),
               existing_nullable=False)
    op.alter_column('rooms', 'code',
               existing_type=sa.VARCHAR(length=5),
               type_=sa.String(length=12),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rooms', 'code',
               existing_type=sa.String(length=12),
               type_=sa.VARCHAR(length=5),
               existing_nullable=False)
    op.alter_column('cards', 'name',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=64),
               existing_nullable=False)
    # ### end Alembic commands ###
