"""empty message

Revision ID: 86de63495c40
Revises: e8c2bccea789
Create Date: 2020-02-11 18:24:03.609779

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '86de63495c40'
down_revision = 'e8c2bccea789'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room_association', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('room_association', sa.Column('discarded_at', sa.DateTime(), nullable=True))
    op.drop_column('room_association', 'date_joined')
    op.drop_column('rooms', 'discarded_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('discarded_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('room_association', sa.Column('date_joined', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('room_association', 'discarded_at')
    op.drop_column('room_association', 'created_at')
    # ### end Alembic commands ###
