"""empty message

Revision ID: 8a7da55369ee
Revises: e76825681e19
Create Date: 2019-12-18 12:09:12.845707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a7da55369ee'
down_revision = 'e76825681e19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('association', sa.Column('id', sa.Integer(), nullable=False))
    op.alter_column('association', 'room_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('association', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('association', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('association', 'room_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('association', 'id')
    # ### end Alembic commands ###
