"""empty message

Revision ID: 8e05634edf07
Revises: 91919e08908f
Create Date: 2020-06-08 21:48:24.152796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e05634edf07'
down_revision = 'b6fd6795a402'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('round_number', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'round_number')
    # ### end Alembic commands ###
