"""empty message

Revision ID: 950197d25121
Revises: bf4037b5b020
Create Date: 2020-05-02 15:07:20.172300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '950197d25121'
down_revision = 'bf4037b5b020'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'username')
    # ### end Alembic commands ###
