"""empty message

Revision ID: 9d58b8648ed6
Revises: 55063cfaebce
Create Date: 2019-12-20 13:56:45.264395

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d58b8648ed6'
down_revision = '55063cfaebce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('state', sa.String(length=1024), nullable=True))
    op.drop_column('rooms', 'scores')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('scores', sa.VARCHAR(length=65536), autoincrement=False, nullable=True))
    op.drop_column('rooms', 'state')
    # ### end Alembic commands ###
