"""empty message

Revision ID: b52d1ceb6798
Revises: 200e5c3ca500
Create Date: 2020-04-26 13:58:43.733248

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b52d1ceb6798'
down_revision = '200e5c3ca500'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('max_points', sa.Integer(), nullable=False))
    op.drop_column('rooms', 'discarded_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('discarded_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('games', 'max_points')
    # ### end Alembic commands ###
