"""empty message

Revision ID: b6fd6795a402
Revises: 4754c7b10a56
Create Date: 2020-05-06 20:27:03.152836

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6fd6795a402'
down_revision = '4754c7b10a56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_color', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_color')
    # ### end Alembic commands ###
